apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - name: image-type
      description: Image type to build 
      type: string
      default: ""
    - description: config.toml file to pass to BIB
      default: ""
      type: string
      name: config-toml
    - description: path to bib yaml file
      default: "bib.yaml"
      name: bib-file
      type: string
    - default: .
      description:
        Path to the source code of an application's component from where
        to build image.
      name: path-context
      type: string
    - default: Dockerfile
      description:
        Path to the Dockerfile inside the context specified by parameter
        path-context
      name: dockerfile
      type: string
    - default: "false"
      description: Force rebuild image
      name: rebuild
      type: string
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "true"
      description: Skip optional checks, set false if you want to run optional checks
      name: skip-optional
      type: string
    - default: "false"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ""
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: "false"
      description: Java build
      name: java
      type: string
    - default: ""
      description:
        Image tag expiration time, time values could be something like
        1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
    - name: additional-tags
      description: Additional tags to apply to the built image
      type: array
      default: []
    - name: build-platforms
      description: List of platforms to build the disk images on. The available
        set of values is determined by the configuration of the multi-platform-controller.
      type: array
      default:
        - linux-root/amd64
  results:
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
  tasks:
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)
        - name: rebuild
          value: $(params.rebuild)
        - name: skip-checks
          value: $(params.skip-checks)
        - name: skip-optional
          value: $(params.skip-optional)
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
        - name: pipelinerun-uid
          value: $(context.pipelineRun.uid)
      taskRef:
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:66e90d31e1386bf516fb548cd3e3f0082b5d0234b8b90dbf9e0d4684b70dbe1a
          - name: kind
            value: task
        resolver: bundles
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: git-clone-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:8ecf57d5a6697ce709bee65b62781efe79a10b0c2b95e05576442b67fbd61744
          - name: kind
            value: task
      when:
        - input: "$(tasks.init.results.build)"
          operator: in
          values:
          - 'true'
      runAfter:
        - init
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.revision)"
        - name: ociStorage
          value: "$(params.output-image).git"
        - name: ociArtifactExpiresAfter
          value: "$(params.image-expires-after)"
        - name: enableSymlinkCheck
          value: false
      workspaces:
        - name: basic-auth
          workspace: git-auth
    - name: prefetch-dependencies
      params:
        - name: input
          value: $(params.prefetch-input)
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
        - name: ociStorage
          value: $(params.output-image).prefetch
        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
        - name: dev-package-managers
          value: "true"
      runAfter:
        - clone-repository
      taskRef:
        params:
          - name: name
            value: prefetch-dependencies-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:1f6e2c9beba52d21c562ba1dea55f579f67e33b80099615bfd2043864896284d
          - name: kind
            value: task
        resolver: bundles
      workspaces:
        - name: git-basic-auth
          workspace: git-auth
        - name: netrc
          workspace: netrc
    - name: build-vm-image
      timeout: "3h0m00s"
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.build-platforms)
      params:
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
        - name: OUTPUT_IMAGE
          value: $(params.output-image)
        - name: PODVM_PAYLOAD_IMAGE
          value: quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-payload@sha256:73a82ac1c252f068f9d046a36dfca7932202ad728f94fc575a332d8707650905
      runAfter:
        - prefetch-dependencies
      taskRef:
        name: build-dm-verity-image
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
    - name: build-image-index
      timeout: "3h0m00s"
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: IMAGES
          value: $(tasks.build-vm-image.results.IMAGE_REFERENCE[*])
      runAfter:
        - build-vm-image
      taskRef:
        params:
          - name: name
            value: build-image-manifest
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-image-manifest:0.1@sha256:a279536c2e73b55e342e4827b4a0e9cf9abed8f27fb4363eea9de09a1da5b421
          - name: kind
            value: task
        resolver: bundles
    - name: apply-tags
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: ADDITIONAL_TAGS
          value:
            - $(params.additional-tags[*])
      runAfter:
        - build-image-index
      taskRef:
        params:
          - name: name
            value: apply-tags
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.1@sha256:1c6f673fe100a49f58aaef62580c8adf0c397790964f4e7bac7fcd3f4d07c92e
          - name: kind
            value: task
        resolver: bundles
    - name: sast-shell-check
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-index
      taskRef:
        params:
          - name: name
            value: sast-shell-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta:0.1@sha256:a7766190229785bc5db9c62af92d46a83ea580a111b4b64a4e27f6caecae9489
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: sast-unicode-check
      params:
        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-index
      taskRef:
        params:
          - name: name
            value: sast-unicode-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta:0.2@sha256:9613b9037e4199495800c2054c13d0479e3335ec94e0f15f031a5bce844003a9
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
  workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
